server:
  port: 10050

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

# 开启 REST 风格接口
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true