# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# docker-compose 版本
version: '2'

# 定义服务用到的网桥
networks:
  ABC:
  PROVIDER:
  SUBSCRIBER:
  # REGULATOR:
  ORDERER:

# 一个服务就是一个容器
services:

  # 服务名 ca_org1 ，也就是一个容器
  ca_provider:
    # 容器使用的镜像
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    # 容器内的环境变量
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Provider
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9201
    # 宿主机和容器的端口映射
    ports:
      - "9201:9201"
    # 用于覆盖容器启动后默认执行的命令
    # 这里在启动 CA Server
    # -b 参数，引入一个管理员账户 admin:adminpw
    # -d 参数，DEBUG 模式启动 CA Server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    # 容器数据卷挂载在宿主机的路径位置
    # 这里的相对路径是相对 compose file 来映射的
    volumes:
      - ../organizations/fabric-ca/providerOrg:/etc/hyperledger/fabric-ca-server
    # 容器名
    container_name: ca_provider
    # 代表当前服务都在哪些网桥内通信
    networks:
      - ABC
      - PROVIDER

  ca_subscriber:
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-Subscriber
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9202
    ports:
      - "9202:9202"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/subscriberOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_subscriber
    networks:
      - ABC
      - SUBSCRIBER

  # ca_regulator:
  #   image: hyperledger/fabric-ca:$CA_IMAGE_TAG
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-Regulator
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=9203
  #   ports:
  #     - "9203:9203"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../organizations/fabric-ca/regulatorOrg:/etc/hyperledger/fabric-ca-server
  #   container_name: ca_regulator
  #   networks:
  #     - ABC
  #     - REGULATOR

  # ca_orderer:
  #   image: hyperledger/fabric-ca:$CA_IMAGE_TAG
  #   environment:
  #     - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  #     - FABRIC_CA_SERVER_CA_NAME=ca-Orderer
  #     - FABRIC_CA_SERVER_TLS_ENABLED=true
  #     - FABRIC_CA_SERVER_PORT=9204
  #   ports:
  #     - "9204:9204"
  #   command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
  #   volumes:
  #     - ../organizations/fabric-ca/ordererOrg:/etc/hyperledger/fabric-ca-server
  #   container_name: ca_orderer
  #   networks:
  #     - ABC
  #     - ORDERER
